services:
  - type: web
    name: smart-recipe-api
    env: python
    plan: free
    buildCommand: |
      cd api
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.8
    autoDeploy: true
